# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hannah J. Kissinger
subtitle: Data-Driven Solutions | Hand-crafted Insights
email:
description: This GitHub portfolio is a place of exploration. Join me on my data analyst journey as I deep dive into dirty data, learn code, and discover insights! 
#>- # this means to ignore newlines until "baseurl:"
 # Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
#twitter_username: username
github_username: hjkissinger
minimal_mistakes_skin: dirt
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Hannah Kissinger"
  avatar : "/assets/images/hjkissinger-pic.jpg"
  bio    : "Interested in learning more about my projects? Let's connect!"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://hjkissinger.github.io"
    #- label: "Twitter"
      #icon: "fab fa-fw fa-twitter-square"
      #url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hjkissinger"
    - label: "LinkedIn"
      icon: "fab fa-brands fa-linkedin"
      url: "https://linkedin.com/in/hannah-j-kissinger-854403116/"

footer:
  links:
    #- label: "Twitter"
     # icon: "fab fa-fw fa-twitter-square"
      #url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hjkissinger"
    - label: "LinkedIn"
      icon: "fab fa-brands fa-linkedin"
      url: "https://linkedin.com/in/hannah-j-kissinger-854403116/"

defaults:
  # _posts
  #- scope:
   #   path: ""
    #  type: posts
    #values:
     # layout: splash
      #author_profile: true
      #read_time: true
      #comments: true
      #share: true
      #related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
      
  - scope:
       path: ""
       values:
         layout: splash
         permalink: /
         hidden: true
         header:
          overlay_color: "#5e616c"
          overlay_image: /assets/images/kari-shea-1SAnrIxw5OY-unsplash.jpg
          actions:
            - label: "<i class='fas fa-download'></i> Install now"
              url: "/docs/quick-start-guide/"
        excerpt: > A flexible two-column Jekyll theme. Perfect for building personal sites, blogs, and portfolios.<br />
        <small><a href="https://github.com/mmistakes/minimal-mistakes/releases/tag/4.24.0">Latest release v4.24.0</a></small>
      feature_row:
         - image_path: /assets/images/kari-shea-1SAnrIxw5OY-unsplash.png
           alt: "customizable"
           title: "Super customizable"
           excerpt: "Everything from the menus, sidebars, comments, and more can be configured or set with YAML Front Matter."
           url: "/docs/configuration/"
           btn_class: "btn--primary"
           btn_label: "Learn more"
         - image_path: /assets/images/kari-shea-1SAnrIxw5OY-unsplash.png
           alt: "fully responsive"
           title: "Responsive layouts"
           excerpt: "Built with HTML5 + CSS3. All layouts are fully responsive with helpers to augment your content."
           url: "/docs/layouts/"
           btn_class: "btn--primary"
           btn_label: "Learn more"
         - image_path: /assets/images/kari-shea-1SAnrIxw5OY-unsplash.png
           alt: "100% free"
           title: "100% free"
           excerpt: "Free to use however you want under the MIT License. Clone it, fork it, customize it... whatever!"
           url: "/docs/license/"
           btn_class: "btn--primary"
           btn_label: "Learn more"      

{% include feature_row %}

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

github: [metadata]
